# Generated by Django 4.1.1 on 2022-09-05 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 일시')),
                ('boj_handle', models.TextField(verbose_name='BOJ 핸들')),
                ('standard_problems_count', models.PositiveIntegerField(default=1, verbose_name='풀어야 하는 문제 수')),
                ('failed_days_count', models.PositiveIntegerField(default=0, verbose_name='문제 풀이를 실패한 날짜 수')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'db_table': 'participants',
            },
        ),
        migrations.CreateModel(
            name='SolveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 일시')),
                ('level', models.IntegerField(default=0, verbose_name='문제 레벨')),
                ('solved_count', models.IntegerField(default=0, verbose_name='해당 문제 레벨에서 푼 문제 수')),
                ('partial_solved_count', models.IntegerField(default=0, verbose_name='해당 문제 레벨에서 부분 성공한 문제 수')),
                ('tried_count', models.IntegerField(default=0, verbose_name='해당 문제 레벨 시도 횟수')),
                ('exp', models.IntegerField(default=0, verbose_name='해당 문제 레벨에서 얻은 경험치')),
                ('standard_date', models.DateField(verbose_name='해당 로그의 기준 날짜')),
                ('is_success', models.BooleanField(default=True)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solve_logs', to='participant.participant', verbose_name='참가자')),
            ],
            options={
                'verbose_name': 'SolveLog',
                'verbose_name_plural': 'SolveLogs',
                'db_table': 'solve_logs',
            },
        ),
        migrations.AddConstraint(
            model_name='solvelog',
            constraint=models.UniqueConstraint(fields=('participant', 'level', 'standard_date'), name='unique_date_level_log_by_participant'),
        ),
    ]
