# Generated by Django 4.1.1 on 2022-09-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solvelog',
            name='is_success',
        ),
    ]
