# Generated by Django 4.1.1 on 2022-09-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_dailysolvelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysolvelog',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
    ]
