# Generated by Django 4.1.1 on 2022-10-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_dailysolvelog_is_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='이름(임시)'),
        ),
        migrations.AddField(
            model_name='participant',
            name='paied_failed_days_count',
            field=models.PositiveIntegerField(default=0, verbose_name='정산된 실패 횟수'),
        ),
    ]
