# Generated by Django 4.1.1 on 2022-10-02 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0005_participant_name_participant_paied_failed_days_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysolvelog',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_solve_logs', to='participant.participant', verbose_name='참가자'),
        ),
        migrations.AlterField(
            model_name='solvelog',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solve_logs', to='participant.participant', verbose_name='참가자'),
        ),
    ]
